config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "foods#index"

  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :public_recipes, only: [:index]
  resources :general_shopping_list, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :measurement_unit, presence: true
  validates :quantity, presence: true

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :cooking_time, presence: true
  validates :preparation_time, presence: true

  def total_food_items
    recipe_foods.select(:food_id).distinct.count
  end

  def total_price
    recipe_foods.includes(:food).sum { |recipe_food| recipe_food.food.price * recipe_food.quantity }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :recipe_id, presence: true
  validates :food_id, presence: true
  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :email, presence: true

  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.all
  end

  def new
    @food = current_user.foods.new
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully saved.'
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])

    if @food.destroy
      flash[:success] = 'Food deleted successfully.'
    else
      flash[:error] = 'Failed to delete food.'
    end
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @missing_foods = current_user.foods.where.not(id: RecipeFood.includes(:recipe)
                             .where(recipes: { user_id: current_user.id }).pluck(:food_id))
    @shopping_list_items = {}
    @total_items = 0
    @total_price = 0.0

    @missing_foods.each do |food|
      quantity = food.quantity
      price = food.price * quantity
      if @shopping_list_items[food.id].present?
        @shopping_list_items[food.id][:quantity] += quantity
        @shopping_list_items[food.id][:price] += price
      else
        @shopping_list_items[food.id] = { food:, quantity:, price: }
      end
      @total_price += price
    end
    @total_items += @missing_foods.select(:id).distinct.count
    @shopping_list_items = @shopping_list_items.values.sort_by { |item| item[:food].name }
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user: current_user)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]
    if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient added successfully!'
    else
      flash[:alert] = 'Failed creating ingredient'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(params[:recipe_id]), notice: 'Ingredient successfully removed.'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipe = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.recipe_foods.where(recipe: @recipe)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    puts params.inspect
    if @recipe.save
      flash[:success] = 'Recipe successfully created'
      redirect_to recipes_path
    else
      flash[:danger] = "Couldn't create recipe"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:success] = 'Recipe deleted!'
    redirect_to recipes_path
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    @recipe.save
    redirect_to recipe_path(@recipe), notice: 'Recipe status updated.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="container px-5">
  <div class="d-flex justify-content-between align-items-center px-5 py-2" >
    <h3 class="pb-3">List of foods</h3>
    <%= link_to "Add Food", new_food_path, class: "btn btn-secondary btn-sm py-2", style: "height: 45px;" %>
  </div>
  <div class="container px-5">
    <table class="table table-sm align-middle table-striped table-hover table-bordered ">
      <thead>
        <tr class="table-active">
          <th scope="col">Food</th>
          <th scope="col">Measurement Unit</th>
          <th scope="col">Unit Price</th>
          <th scope="col"> Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @foods.each do |food| %>
          <tr scope="row">
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= number_to_currency(food.price) %></td>
            <td>
              <%= button_to "Delete", food_path(food), class: "btn btn-link", method: :delete, data: { confirm: "Are you sure you want to delete #{food.name}?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container width-50">
  <%= form_for @food, url: foods_path, local: true, data: { turbo: false }, method: :post do |f| %>
    <% if @food.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @food.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h3 class="bg-body-tertiary rounded py-3">New Food Item</h3>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :measurement_unit %>
      <%= f.text_field :measurement_unit, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :quantity %>
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
      <%= f.submit "Save Food", class: "btn btn-secondary" %>
      <%= link_to "Cancel", foods_path, class: "btn btn-secondary cancel-link" %>
    </div>
  <% end %>
</div>

app/views/general_shopping_list/index.html.erb
<div class="container width-50">
  <h2>Shopping List</h2>
  <div class="d-flex justify-content-between">
    <p>Amount of food items to buy: <%= @total_items %></p>
    <p>Total value of food needed: <%= number_to_currency(@total_price) %></p>
  </div>
  <div class="table-responsive">
    <% if @shopping_list_items.present? %>
      <table class="table align-middle table-bordered border-primary">
        <thead>
          <tr class="table-active">
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <% @shopping_list_items.each do |item| %>
            <tr scope="row">
              <td><%= item[:food].name %></td>
              <td><%= item[:quantity] %></td>
              <td><%= number_to_currency(item[:price]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No missing food items found.</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render 'shared/menu' %>
    <main class="container">    
      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="container px-5 mt-0 width-50">
  
  <ul class="list-group">
    <li class="list-group-item list-group-item-secondary" aria-current="true"><h2>Public Recipes</h2></li>
    <% @recipes.each do |recipe| %>
      <li class="list-group-item shadow-sm justify-content-between align-items-center mb-3">
        <div class="d-flex justify-content-between">
          <div class="d-flex flex-column mb-3">
            <h4><%= link_to recipe.name, recipe_path(recipe), class: "text-decoration-none" %></h4>
            <p>By: <%= recipe.user.name %></p>
          </div>
          <div class="d-flex flex-column mb-3">
            <p>Total food items: <%= recipe.total_food_items %></p>
            <p>Total price: <%= number_to_currency(recipe.total_price) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/recipe_foods/new.html.erb
<div class="container width-50">
  <h3 class="shadow-sm p-3 bg-body-tertiary rounded">Add Ingredient</h3>
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path do |form| %>

    <%= form.label :food_id, 'Food Name', class: "form-label" %>
    <%= form.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class:'form-select'} %>
    <br>
    <%= form.label :quantity, 'Quantity', class: "form-label" %>
    <%= form.number_field :quantity, class:'form-control' %>
    <br>
    <%= form.submit "Add Ingredient", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="container px-5">
  <div class="d-flex justify-content-between px-5 py-2" >
    <h3 class="pb-3">List of recipes</h3>
  </div>
  <div class="container px-5">
    <% if @recipe.blank? %>
      <p>No recipe available</p>
    <% else %>
      <% @recipe.each do |recipe| %>
        <div class="container-fluid mb-4 border recipe">
          <a href=<%= url_for(recipe_path(recipe)) %> class = 'text-decoration-none' >
            <div class="row border border-1 align-items-center">
              <div class="col-sm-3 p-3">
                <h4><%= recipe.name %></h4>
              </div>
              <div class="col col-sm-9 overflow-hidden">
                <p><%= recipe.description %></p>
              </div>
            </div>
          </a>
          <div class="mb-2 " >
            <% if current_user.id == recipe.user_id %>
              <%= button_to "Remove", recipe, method: :delete, class: 'btn btn-danger mt-2' %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= link_to "Add Recipe", new_recipe_path, class: "btn btn-outline-primary float-right" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container width-50">
  <h3 class="shadow-sm p-3 bg-body-tertiary rounded">New Recipe</h3>
  <%= form_for @recipe, url: recipes_path, local: true, data: { turbo: false }, method: :post do |form| %>
    <% if @recipe.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="mb-3">
      <%= form.label :description %>
      <%= form.text_area :description, class: "recipe_text_area" %>
    </div>
    <div class="mb-3">
      <%= form.label :preparation_time %>
      <%= form.text_field :preparation_time %>
    </div>
    <div class="mb-3">
      <%= form.label :cooking_time %>
      <%= form.text_field :cooking_time %>
    </div>
    <div class="mb-3">
      <%= form.label :public %>
      <%= form.check_box :public%>
    </div>
    <div>
      <%= form.submit "Create Recipe", class: "btn btn-primary" %>
      <%= link_to "Cancel", recipes_path, class: "btn btn-primary cancel-link" %>
    </div>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<div class="container width-50">
  <h2>Shopping List</h2>
  <div class="d-flex justify-content-between">
    <div>
      <p>Total number of items: <%= @total_items %></p>
      <p>Total price: <%= number_to_currency(@total_price) %></p>
    </div>
    <p>Recipe: <%= @recipe.name %></p>
  </div>
  <div class="table-responsive">
    <% if @shopping_list_items.present? %>
      <table class="table align-middle table-bordered border-primary">
        <thead>
          <tr class="table-active">
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <% @shopping_list_items.each do |item| %>
            <tr scope="row">
              <td><%= item[:food].name %></td>
              <td><%= item[:quantity] %></td>
              <td><%= number_to_currency(item[:price]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No missing food items found.</p>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container px-5">
  <h2 class="text-center mt-4 mb-4"><%= @recipe.name %></h2>
  <div class="d-flex justify-content-between">
    <div>
      <p><span class="font-weight-bold">Preparation Time:</span> <%= @recipe.preparation_time %></p>
      <p><span class="font-weight-bold">Cooking Time:</span> <%= @recipe.cooking_time %></p>
      <p><span class="font-weight-bold">Steps:</span></p>
      <p><%= @recipe.description %></p>
    </div>
    <div>
      <% if current_user.id == @recipe.user_id %>
        <% if @recipe.public %>
          <p><span class="font-weight-bold">Current Status:</span> Public</p>
          <%= button_to "Change", recipe_path(@recipe), method: :patch, class: 'btn btn-success float-right' %>
        <% else %>
          <p><span class="font-weight-bold">Current Status:</span> Private</p>
          <%= button_to "Change", recipe_path(@recipe), method: :patch, class: 'btn btn-secondary float-right' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-between text-decoration-none mb-5">
    <%= link_to "Generate shopping list",general_shopping_list_index_path, class: 'btn btn-secondary' %>
    <% if current_user.id == @recipe.user_id %>
      <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-secondary' %>
    <% end %>
  </div>
  <table class="table table-sm  table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
      <tbody class="table-group-divider">
      <% @ingredients.each do |ingredient|%>
        <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= ingredient.quantity%> <%= ingredient.food.measurement_unit %></td>
          <td>$ <%= ingredient.food.price * ingredient.quantity %></td>
          <td>
          <% if current_user.id == @recipe.user_id %>
            <%= button_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete,  class: "btn btn-link" %>
          <%else%>
            <p>Actions Not allowed</p>
          <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm" style="background-color: #e3f2fd;">
	<div class="container">
		<a class="navbar-brand" href="/">Recipe App</a>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Food
          </button>
          <ul class="dropdown-menu dropdown-menu">
            <li><a class="dropdown-item" href="/foods">Foods List</a></li>
            <li><a class="dropdown-item" href="/foods/new">Add New Food</a></li>
            <li><a class="dropdown-item" href="/general_shopping_list">General Shopping List</a></li>
          </ul>
        </li> 
        <li class="nav-item dropdown">
          <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Recipe
          </button>
          <ul class="dropdown-menu dropdown-menu">
            <li><a class="dropdown-item" href="/recipes">Recipes List</a></li>
            <li><a class="dropdown-item" href="/recipes/new">Add New Recipe</a></li>
            <li><a class="dropdown-item" href="/public_recipes">Public Recipies</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <% if current_user %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-outline" %>
          <% else %>
            <%= button_to "Sign In", new_user_session_path, class: "btn btn-small btn-outline" %>
          <% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>